import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const server=createServer(async(req,res)=>{try{let file=new URL(req.url,'http://localhost').pathname;if(/^\/s\//.test(file))file='/shirt.html';if(/^\/d\//.test(file))file='/share.html';if(/^\/gift\//.test(file))file='/gift.html';if(file==='/')file='/index.html';const target=path.resolve('dist','.'+file);if(!target.startsWith(path.resolve('dist')+path.sep))throw new Error();const data=await readFile(target);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(data);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(4175,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/tmp/chromium',args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const uid='00000000-0000-4000-8000-000000000041';const profile='10000000-0000-4000-8000-000000000041';const revision='20000000-0000-4000-8000-000000000041';const variant='30000000-0000-4000-8000-000000000041';const order='40000000-0000-4000-8000-000000000041';const shirt='50000000-0000-4000-8000-000000000041';const token='a'.repeat(32);const user={id:uid,email:'test@example.invalid',aud:'authenticated',is_anonymous:false,role:'authenticated',app_metadata:{},user_metadata:{}};const jwt=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test';const session={access_token:jwt,refresh_token:'test',token_type:'bearer',expires_at:Math.floor(Date.now()/1000)+3600,user};await context.addInitScript(({session})=>localStorage.setItem('sb-dompwdardnqvmoncawrk-auth-token',JSON.stringify(session)),{session});
 const design={id:revision,line1:'A real human',line2:'who loves soccer',font_key:'modern',icon_key:'soccer',shirt_color:'black',accent_color:'#22b8ff',revision_number:3,created_at:new Date().toISOString()};let settings=null;let gifted=false;let checkoutRequest=null;
 await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://dompwdardnqvmoncawrk.supabase.co/**',async route=>{const req=route.request();const u=new URL(req.url());const name=u.pathname.split('/').pop();let body=[];if(name==='user')body=user;else if(name==='profiles')body={id:profile,full_name:'Test Human',archived_at:null};else if(name==='read_share')body={design,version:3};else if(name==='read_shirt')body={handle:null,story:'Soccer makes my day.',design};else if(name==='read_gift')body={message:'Pick your favorite!',status:'invited'};else if(name==='my_network')body=[{depth:1,handle:null},{depth:2,handle:'another_human'}];else if(name==='my_referrals')body=[{status:'qualified',reward_minor:300,currency:'USD',created_at:design.created_at}];else if(name==='gift_submissions')body=[];else if(name==='gift_invite')body=token;else if(name==='gift_reply'){gifted=true;body=null;}else if(name==='share_design')body=token;else if(name==='list_my_designs')body=[{id:revision,name:'My favorite',revision:design,updated_at:design.created_at}];else if(name==='design_revisions')body=req.headers().accept?.includes('object')?design:[design];else if(name==='designs')body={id:revision,name:'My favorite',archived_at:null};else if(name==='product_variants')body=[{id:variant,product_name:'Test shirt',color_key:'black',size_key:'M',price_minor:2799,currency:'USD',measurements:{chest_width_inches:20},fit_notes:'Test fit'}];else if(name==='shirts')body=[{id:shirt,user_id:profile,wearer_id:null,qr_token:token,qr_state:'active',story:'My story',story_public:false,design_public:false,created_at:design.created_at}];else if(name==='shirt_settings'){settings=req.postDataJSON();body=null;}else if(name==='orders')body=req.headers().accept?.includes('object')?{order_number:7,created_at:design.created_at,payment_status:'paid',fulfillment_status:'shipped',subtotal_minor:2799,shipping_minor:500,tax_minor:0,discount_minor:0,credit_minor:0,total_minor:3299,currency:'USD'}:[{id:order,order_number:7,created_at:design.created_at,payment_status:'paid',fulfillment_status:'shipped',total_minor:3299,currency:'USD'}];else if(name==='order_items')body=[{revision_id:revision,quantity:1,unit_price_minor:2799,product_snapshot:{product_name:'Test shirt',color:'black',size:'M'},personalization_snapshot:design}];else if(name==='shipments')body=[{carrier:'Test carrier',tracking_number:'TRACK123',shipped_at:design.created_at}];else if(name==='design_shares')body=[{token,created_at:design.created_at,revoked_at:null}];await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});});
 await context.route('**/api/checkout',async r=>{checkoutRequest=r.request().postDataJSON();await r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Ordering is not open yet.'})});});
 await page.goto('http://127.0.0.1:4175/d/'+token);await page.getByRole('button',{name:'Make my own version'}).waitFor();assert.equal(await page.locator('img.proof-art').count(),1);await page.screenshot({path:'/tmp/notai-shared-design-mobile.png',fullPage:true});
 await page.goto('http://127.0.0.1:4175/s/'+token);await page.getByText('Soccer makes my day.').waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('notai-referral')).token),token);
 await page.goto('http://127.0.0.1:4175/proof.html?revision='+revision);await page.getByRole('link',{name:'Choose size and order'}).waitFor();
 await page.goto('http://127.0.0.1:4175/checkout.html?revision='+revision);await page.getByLabel('Shirt size',{exact:true}).waitFor();await page.getByLabel('I have reviewed').check();await page.getByLabel('Apply available store credit').check();await page.getByRole('button',{name:'Continue to secure checkout'}).click();await page.getByRole('status').filter({hasText:'Ordering is not open yet.'}).waitFor();assert.equal(checkoutRequest.referral,token);assert.equal(checkoutRequest.use_credit,true);assert.equal(checkoutRequest.variant_id,variant);
 await page.goto('http://127.0.0.1:4175/network.html');await page.getByText('Private human · Inspired by you').waitFor();await page.getByLabel('The story behind this shirt').fill('My changed story');await page.getByLabel('Show my story').check();await page.getByRole('button',{name:'Save shirt privacy'}).click();await page.getByRole('status').filter({hasText:'privacy settings saved'}).waitFor();assert.equal(settings.p_story_public,true);assert.equal(settings.p_design_public,false);await page.screenshot({path:'/tmp/notai-network-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.goto('http://127.0.0.1:4175/gifts.html');await page.getByLabel('Message for your recipient').fill('Your choice!');await page.getByRole('button',{name:'Create gift invitation'}).click();await page.getByRole('textbox',{name:'Gift invitation link'}).waitFor();
 await page.goto('http://127.0.0.1:4175/gift/'+token);await page.getByRole('button',{name:'Share this choice with the giver'}).click();await page.getByRole('status').filter({hasText:'giver can now review'}).waitFor();assert.equal(gifted,true);
 await page.goto('http://127.0.0.1:4175/order.html?id='+order);await page.getByText('TRACK123',{exact:false}).waitFor();await page.getByRole('link',{name:'Order another size'}).waitFor();
 await page.goto('http://127.0.0.1:4175/');await page.locator('#starter').selectOption('family');assert.equal(await page.locator('#l1').inputValue(),'proud of my people');await page.screenshot({path:'/tmp/notai-customizer-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);console.log('PASS: shared designs, QR pages/referral capture, proof, checkout request, privacy settings, network, gift invitation/reply, order tracking, design starters, mobile layout');
}finally{await browser.close();server.close();}
