import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const server=createServer(async(req,res)=>{try{let file=new URL(req.url,'http://localhost').pathname;if(/^\/s\//.test(file))file='/shirt.html';if(/^\/d\//.test(file))file='/share.html';if(/^\/gift\//.test(file))file='/gift.html';if(file==='/')file='/index.html';const target=path.resolve('dist','.'+file);if(!target.startsWith(path.resolve('dist')+path.sep))throw new Error();const data=await readFile(target);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(data);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(4181,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/tmp/chromium',args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const uid='00000000-0000-4000-8000-000000000041';const profile='10000000-0000-4000-8000-000000000041';const revision='20000000-0000-4000-8000-000000000041';const variantUuid='30000000-0000-4000-8000-000000000041';const order='40000000-0000-4000-8000-000000000041';const shirt='50000000-0000-4000-8000-000000000041';const token='a'.repeat(32);const user={id:uid,email:'test@example.invalid',aud:'authenticated',is_anonymous:false,role:'authenticated',app_metadata:{},user_metadata:{}};const jwt=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test';const session={access_token:jwt,refresh_token:'test',token_type:'bearer',expires_at:Math.floor(Date.now()/1000)+3600,user};await context.addInitScript(({session})=>localStorage.setItem('sb-dompwdardnqvmoncawrk-auth-token',JSON.stringify(session)),{session});


const orderData={id:order,order_number:101,payment_status:'paid',net_revenue:3200,cogs_actual:0,cogs_estimate:1500,fees_actual:0,fees_estimate:0,cogs_complete:false,fees_complete:false,gross_profit:null,gross_margin_percent:null,contribution:null,refunded_minor:0,recorded_refund_total_minor:null,recorded_refund_tax_minor:null,refund_estimated:false};
const report={orders:[orderData],entries:[],entry_count:0,credit_liability:500,reviews:[],summary:{order_count:1,net_revenue:3200,refunds_excluding_tax:0,recorded_cogs:0,recorded_fees:0,gross_profit:null,gross_margin_percent:null,contribution:null,operating_expenses:0,after_expenses:null,net_customer_tax:280,missing_cogs:1,missing_fees:1,estimated_refunds:0}};let mutations=[],queries=[],denied=false;
await context.route('https://dompwdardnqvmoncawrk.supabase.co/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({auth_user_id:uid})}));
await context.route('**/api/finance**',async r=>{if(r.request().method()==='POST')mutations.push(r.request().postDataJSON());else queries.push(r.request().url());await r.fulfill({status:denied?403:200,contentType:'application/json',body:JSON.stringify(denied?{error:'Owner access required.'}:r.request().method()==='POST'?{saved:true}:report)});});
await page.goto('http://127.0.0.1:4181/finances.html');await page.locator('#coverage').waitFor();await page.getByText('1 paid orders.',{exact:false}).waitFor();assert.ok((await page.locator('#finance-summary').innerText()).includes('Not reviewed'));await page.screenshot({path:'/tmp/notai-finance-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.getByRole('link',{name:'Review order costs',exact:true}).click();await page.getByText('Costs for order #101').waitFor();await page.getByLabel('Amount (USD)',{exact:true}).fill('17.25');await page.getByLabel('Description',{exact:true}).fill('Printful invoice');await page.getByRole('button',{name:'Save financial entry'}).click();await page.getByText('Financial record saved.',{exact:true}).waitFor();assert.equal(mutations[0].amount_minor,1725);assert.equal(mutations[0].order_id,order);assert.equal(mutations[0].basis,'actual');assert.match(mutations[0].request_key,/^[a-f0-9-]{36}$/);
await page.locator('#cogs-complete').check();await page.locator('#fees-complete').check();await page.locator('#refund-tax').fill('1.20');await page.getByRole('button',{name:'Save cost review'}).click();await page.waitForTimeout(100);assert.equal(mutations.at(-1).refund_tax_minor,120);assert.equal(mutations.at(-1).cogs_complete,true);await page.setViewportSize({width:320,height:800});await page.screenshot({path:'/tmp/notai-finance-detail-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.goto('http://127.0.0.1:4181/finance-entry.html');await page.locator('#finance-content').waitFor({state:'visible'});await page.getByLabel('Amount (USD)',{exact:true}).fill('10');await page.getByLabel('Description',{exact:true}).fill('Hosting credit');await page.locator('#cost-credit').check();await page.getByRole('button',{name:'Save financial entry'}).click();await page.waitForTimeout(100);assert.equal(mutations.at(-1).amount_minor,-1000);assert.equal(mutations.at(-1).category,'opex_software');assert.equal(mutations.at(-1).order_id,null);
denied=true;await page.goto('http://127.0.0.1:4181/finances.html');await page.getByText('Owner access required.',{exact:true}).waitFor();assert.equal(await page.locator('#finance-content').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS: incomplete margins, order cost cents, review/refund tax, expense credit, owner denial and 320/390px layouts');
}finally{await browser.close();server.close();}
