import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const server=createServer(async(req,res)=>{try{let file=new URL(req.url,'http://localhost').pathname;if(/^\/s\//.test(file))file='/shirt.html';if(/^\/d\//.test(file))file='/share.html';if(/^\/gift\//.test(file))file='/gift.html';if(file==='/')file='/index.html';const target=path.resolve('dist','.'+file);if(!target.startsWith(path.resolve('dist')+path.sep))throw new Error();const data=await readFile(target);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(data);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(4179,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/tmp/chromium',args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const uid='00000000-0000-4000-8000-000000000041';const profile='10000000-0000-4000-8000-000000000041';const revision='20000000-0000-4000-8000-000000000041';const variantUuid='30000000-0000-4000-8000-000000000041';const order='40000000-0000-4000-8000-000000000041';const shirt='50000000-0000-4000-8000-000000000041';const token='a'.repeat(32);const user={id:uid,email:'test@example.invalid',aud:'authenticated',is_anonymous:false,role:'authenticated',app_metadata:{},user_metadata:{}};const jwt=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test';const session={access_token:jwt,refresh_token:'test',token_type:'bearer',expires_at:Math.floor(Date.now()/1000)+3600,user};await context.addInitScript(({session})=>localStorage.setItem('sb-dompwdardnqvmoncawrk-auth-token',JSON.stringify(session)),{session});

const variant={id:variantUuid,sku:'BLACK_M',product_name:'Cotton tee',color_key:'black',size_key:'M',price_minor:2799,currency:'USD',active:false,fulfillment_provider:'Manual',provider_variant_id:''};
let body={readiness:{database:true,stripe:false,webhook:false,enabled:false,mode:'missing'},settings:{ordering_open:false,shipping_minor:599,fulfillment_note:'Made to order'},variants:[variant],orders:[{id:order,order_number:7,payment_status:'paid',fulfillment_status:'unfulfilled',total_minor:3398,currency:'USD'}]};const requests=[];
await context.route('https://dompwdardnqvmoncawrk.supabase.co/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({auth_user_id:uid})}));
await context.route('**/api/owner',async r=>{if(r.request().method()==='POST'){const b=r.request().postDataJSON();requests.push(b);if(b.action==='settings')body.settings=b;if(b.action==='production')body.orders[0].fulfillment_status='in_production';}await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(r.request().method()==='POST'?{saved:true}:body)});});
await page.goto('http://127.0.0.1:4179/owner.html');await page.getByText('Payment mode: missing.',{exact:false}).waitFor();await page.getByRole('button',{name:'Edit product'}).click();assert.equal(await page.getByLabel('Unique SKU').inputValue(),'BLACK_M');await page.getByLabel('Shirt price (USD)').fill('29.99');await page.getByRole('button',{name:'Save product',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved.'}).waitFor();assert.equal(requests[0].price_minor,2999);await page.getByLabel('Flat shipping per order').fill('6.99');await page.getByRole('button',{name:'Save shop settings'}).click();await page.waitForTimeout(100);assert.equal(requests.at(-1).shipping_minor,699);await page.getByRole('button',{name:'Start production'}).click();await page.getByText('in production',{exact:false}).waitFor();assert.equal(requests.at(-1).action,'production');await page.screenshot({path:'/tmp/notai-owner-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.setViewportSize({width:320,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
await context.unroute('**/api/owner');await context.route('**/api/owner',r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:'Owner access required.'})}));await page.reload();await page.getByRole('status').filter({hasText:'Owner access required.'}).waitFor();assert.equal(await page.locator('#owner-content').isVisible(),false);console.log('PASS owner setup/product/shipping/production, non-owner denial, mobile layout');
}finally{await browser.close();server.close();}
