import {createClient} from '@supabase/supabase-js';
import {authenticated,db,executionGate} from './server.js';
import {SUPABASE_URL,SUPABASE_KEY} from '../src/config.js';
export async function owner(req){const user=await authenticated(req);const scoped=createClient(process.env.SUPABASE_URL||SUPABASE_URL,process.env.SUPABASE_PUBLISHABLE_KEY||SUPABASE_KEY,{global:{headers:{Authorization:req.headers.authorization}},auth:{persistSession:false}});const membership=await scoped.from('shop_owners').select('auth_user_id').eq('auth_user_id',user.id).maybeSingle();if(membership.error||!membership.data)throw Object.assign(new Error('Owner access required.'),{status:403});return user;}
export async function settings(store=db()){const r=await store.from('shop_settings').select('*').eq('id',true).single();if(r.error)throw r.error;return r.data;}
export function readiness(){return {database:Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY),stripe:Boolean(process.env.STRIPE_SECRET_KEY),webhook:Boolean(process.env.STRIPE_WEBHOOK_SECRET),enabled:process.env.NOTAI_CHECKOUT_ENABLED==='true',mode:/^(sk|rk)_live_/.test(process.env.STRIPE_SECRET_KEY||'')?'live':/^(sk|rk)_test_/.test(process.env.STRIPE_SECRET_KEY||'')?'test':'missing'};}
export function ready(r){return r.database&&r.stripe&&r.webhook&&r.enabled&&r.mode!=='missing'&&(process.env.VERCEL_ENV!=='production'||r.mode==='live');}
export function validateSettings(b){if(typeof b.ordering_open!=='boolean'||!Number.isInteger(b.shipping_minor)||b.shipping_minor<0||b.shipping_minor>100000||typeof b.fulfillment_note!=='string'||b.fulfillment_note.length>500)throw Object.assign(new Error('Check shipping and fulfillment settings.'),{status:400});return {ordering_open:b.ordering_open,shipping_minor:b.shipping_minor,fulfillment_note:b.fulfillment_note,updated_at:new Date().toISOString()};}
export function validateVariant(b){if(typeof b.sku!=='string'||!/^[A-Za-z0-9_-]{1,80}$/.test(b.sku)||typeof b.product_name!=='string'||!b.product_name.trim()||b.product_name.length>100||!['black','charcoal','navy','white'].includes(b.color_key)||!['XS','S','M','L','XL','2XL'].includes(b.size_key)||!Number.isInteger(b.price_minor)||b.price_minor<50||b.price_minor>100000||typeof b.active!=='boolean'||typeof b.fulfillment_provider!=='string'||b.fulfillment_provider.length>100||typeof b.provider_variant_id!=='string'||b.provider_variant_id.length>100)throw Object.assign(new Error('Check the product fields and price.'),{status:400});return Object.fromEntries(['sku','product_name','color_key','size_key','price_minor','active','fulfillment_provider','provider_variant_id'].map(k=>[k,b[k]]).concat([['currency','USD']]));}
export function merchantWrites(){executionGate();}
