import {client} from './member.js';
import {icons,fonts} from './design-model.js';
const $=id=>document.getElementById(id);
const stage=document.querySelector('.stage'),tee=document.querySelector('.tee');
let personalPhoto=null,photoVersion=0,photoLoading=false;
const signature=()=>JSON.stringify({design:window.notaiDesigner.read(),photo:photoVersion});
let generatedFor=null,pending=false,generation=0;
function mode(ai){const available=generatedFor===signature();const show=ai&&(pending||available);$('aiResult').hidden=!show;tee.hidden=show;$('designView').setAttribute('aria-pressed',String(!show));$('aiView').setAttribute('aria-pressed',String(show));$('preview-kind').textContent=show?(pending?'Creating AI preview':'AI illustration'):'Live design';document.querySelector('.tabs').hidden=show;}
function counts(){$('word-count').textContent=`First line ${Array.from($('l1').value).length}/32 · Second line ${Array.from($('l2').value).length}/32`;}
$('designView').onclick=()=>mode(false);$('aiView').onclick=()=>mode(true);
for(const id of ['frontBtn','backBtn'])$(id).addEventListener('click',()=>mode(false));
window.addEventListener('notai:design-changed',()=>{counts();if(generatedFor&&generatedFor!==signature()){generatedFor=null;$('download-preview').hidden=true;$('download-preview').removeAttribute('href');$('aiImage').hidden=true;$('aiImage').removeAttribute('src');$('aiView').disabled=!pending;$('aiStatus').textContent='Your design changed. Generate a new AI preview to see this version.';mode(false);}else if(pending){mode(false);$('aiStatus').textContent='You can keep editing. A preview will appear only if it matches your current design.';}});
$('aiPreviewBtn').onclick=async()=>{if(pending||photoLoading)return;if(personalPhoto&&!$('photo-consent').checked){$('photo-status').textContent='Confirm your consent before creating a photo preview.';$('personal-preview').open=true;return;}const session=await client.auth.getSession();if(!session.data.session||session.data.session.user?.is_anonymous){rememberDesign();$('aiStatus').textContent='Sign in and complete your profile to generate image previews. Your design is kept in this browser tab. A selected photo will be cleared if you leave this page.';$('preview-signin').hidden=false;$('personal-preview').open=true;return;}if(generatedFor===signature()){mode(true);return;}const design=window.notaiDesigner.read(),requestSignature=signature(),id=++generation;pending=true;$('aiPreviewBtn').disabled=true;$('aiPreviewBtn').textContent='Creating your preview…';$('aiView').disabled=false;$('aiProgress').hidden=false;$('aiImage').hidden=true;$('aiStatus').textContent='Creating an AI illustration of this design. You can switch back to Design view anytime.';mode(true);stage.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),180000);
try{const artworkDataUrl=await window.notaiDesigner.artworkPng();const baseImageDataUrl=personalPhoto?null:await imageToDataURL(`shirt-${design.shirt}-front.png`);if(signature()!==requestSignature)throw new Error('design_changed');const r=await fetch('/api/generate-preview',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.data.session.access_token},signal:controller.signal,body:JSON.stringify({baseImageDataUrl,personalPhotoDataUrl:personalPhoto,photoConsent:personalPhoto?$('photo-consent').checked:undefined,artworkDataUrl,shirtColor:design.shirt,line1:design.line1,line2:design.line2,font:design.font,accent:design.accent,symbol:design.symbol})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===401?'sign_in':r.status===429?'rate_limit':'unavailable');if(signature()!==requestSignature||id!==generation)throw new Error('design_changed');if(typeof data.image!=='string'||(!data.image.startsWith('data:image/')&&!data.image.startsWith('https://')))throw new Error('unavailable');$('aiImage').src=data.image;await $('aiImage').decode();if(signature()!==requestSignature)throw new Error('design_changed');generatedFor=requestSignature;$('aiImage').hidden=false;$('download-preview').href=data.image;$('download-preview').hidden=false;$('aiStatus').textContent='Your AI illustration is ready. Switch between the views to compare. Your saved design remains the print reference.';pending=false;mode(true);
}catch(e){generatedFor=null;$('download-preview').hidden=true;pending=false;mode(false);$('aiStatus').textContent=e.message==='design_changed'?'Your design changed while the preview was being made. Generate a new preview when you are ready.':e.message==='sign_in'?'Please sign in again to create a preview. Your design is safe.':e.message==='rate_limit'?'Complete your profile first, or try again later. Each account has three image-preview attempts per 24 hours; previews may also be busy.':e.name==='AbortError'?'The preview took too long. You can try again; your design is safe.':'AI preview is temporarily unavailable. You can keep designing and saving your shirt, then try again later.';}
finally{clearTimeout(timeout);pending=false;$('aiProgress').hidden=true;$('aiView').disabled=generatedFor!==signature();$('aiPreviewBtn').disabled=false;$('aiPreviewBtn').textContent=generatedFor?'View my AI preview ↗':personalPhoto?'See me in this shirt ↗':'See a realistic AI preview ↗';}};
counts();mode(false);

function rememberDesign(){try{const d=window.notaiDesigner.read();sessionStorage.setItem('notai-unsaved-design',JSON.stringify({name:$('design-name').value,design:{line1:d.line1,line2:d.line2,icon_key:Object.keys(icons).find(k=>icons[k]===d.symbol),font_key:Object.keys(fonts).find(k=>fonts[k]===d.font),accent_color:d.accent,shirt_color:d.shirt}}));}catch{}}
function resetReference(){photoVersion++;generatedFor=null;$('aiImage').hidden=true;$('aiImage').removeAttribute('src');$('download-preview').hidden=true;$('download-preview').removeAttribute('href');$('aiView').disabled=!pending;mode(false);$('aiPreviewBtn').textContent=personalPhoto?'See me in this shirt ↗':'See a realistic AI preview ↗';}
$('personal-photo').onchange=async()=>{const file=$('personal-photo').files[0];if(!file)return;let bitmap;photoLoading=true;$('aiPreviewBtn').disabled=true;$('photo-status').textContent='Preparing your photo privately in this browser…';try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15000000)throw new Error('Choose a JPEG, PNG or WebP photo smaller than 15 MB.');bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});if(bitmap.width<200||bitmap.height<200||bitmap.width*bitmap.height>30000000)throw new Error('Choose a clear photo at least 200 pixels on each side and under 30 megapixels.');const scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);let compressed=canvas.toDataURL('image/jpeg',.85);if(compressed.length>750000)compressed=canvas.toDataURL('image/jpeg',.65);if(compressed.length>750000)throw new Error('This photo is still too large. Try a simpler or smaller image.');personalPhoto=compressed;$('photo-thumb').src=compressed;$('photo-selected').hidden=false;$('photo-consent').checked=false;resetReference();$('photo-status').textContent='Photo ready. Confirm consent, then choose See me in this shirt. Nothing has been uploaded yet.';}catch(e){$('photo-status').textContent=e.message;}finally{bitmap?.close();$('personal-photo').value='';photoLoading=false;$('aiPreviewBtn').disabled=pending;}};
$('remove-photo').onclick=()=>{personalPhoto=null;$('photo-thumb').removeAttribute('src');$('photo-selected').hidden=true;$('photo-consent').checked=false;resetReference();$('photo-status').textContent='Photo removed from this page.';};
$('preview-signin').onclick=rememberDesign;
client.auth.getSession().then(({data})=>{$('preview-signin').hidden=Boolean(data.session&&!data.session.user?.is_anonymous);});

window.addEventListener('pagehide',()=>{personalPhoto=null;photoVersion++;$('photo-thumb').removeAttribute('src');$('aiImage').removeAttribute('src');$('download-preview').removeAttribute('href');$('download-preview').hidden=true;$('photo-selected').hidden=true;$('photo-consent').checked=false;generatedFor=null;mode(false);$('aiView').disabled=true;$('aiImage').hidden=true;});
