const $=id=>document.getElementById(id);
const stage=document.querySelector('.stage'),tee=document.querySelector('.tee');
const signature=()=>JSON.stringify(window.notaiDesigner.read());
let generatedFor=null,pending=false,generation=0;
function mode(ai){const available=generatedFor===signature();const show=ai&&(pending||available);$('aiResult').hidden=!show;tee.hidden=show;$('designView').setAttribute('aria-pressed',String(!show));$('aiView').setAttribute('aria-pressed',String(show));$('preview-kind').textContent=show?(pending?'Creating AI preview':'AI illustration'):'Live design';document.querySelector('.tabs').hidden=show;}
function counts(){$('word-count').textContent=`First line ${Array.from($('l1').value).length}/32 · Second line ${Array.from($('l2').value).length}/32`;}
$('designView').onclick=()=>mode(false);$('aiView').onclick=()=>mode(true);
for(const id of ['frontBtn','backBtn'])$(id).addEventListener('click',()=>mode(false));
window.addEventListener('notai:design-changed',()=>{counts();if(generatedFor&&generatedFor!==signature()){generatedFor=null;$('aiImage').hidden=true;$('aiView').disabled=!pending;$('aiStatus').textContent='Your design changed. Generate a new AI preview to see this version.';mode(false);}else if(pending){mode(false);$('aiStatus').textContent='You can keep editing. A preview will appear only if it matches your current design.';}});
$('aiPreviewBtn').onclick=async()=>{if(pending)return;if(generatedFor===signature()){mode(true);return;}const design=window.notaiDesigner.read(),requestSignature=JSON.stringify(design),id=++generation;pending=true;$('aiPreviewBtn').disabled=true;$('aiPreviewBtn').textContent='Creating your preview…';$('aiView').disabled=false;$('aiProgress').hidden=false;$('aiImage').hidden=true;$('aiStatus').textContent='Creating an AI illustration of this design. You can switch back to Design view anytime.';mode(true);stage.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),180000);
try{const artworkDataUrl=await window.notaiDesigner.artworkPng();const baseImageDataUrl=await imageToDataURL(`shirt-${design.shirt}-front.png`);if(signature()!==requestSignature)throw new Error('design_changed');const r=await fetch('/api/generate-preview',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({baseImageDataUrl,artworkDataUrl,shirtColor:design.shirt,line1:design.line1,line2:design.line2,font:design.font,accent:design.accent,symbol:design.symbol})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===429?'rate_limit':'unavailable');if(signature()!==requestSignature||id!==generation)throw new Error('design_changed');if(typeof data.image!=='string'||(!data.image.startsWith('data:image/')&&!data.image.startsWith('https://')))throw new Error('unavailable');$('aiImage').src=data.image;await $('aiImage').decode();if(signature()!==requestSignature)throw new Error('design_changed');generatedFor=requestSignature;$('aiImage').hidden=false;$('aiStatus').textContent='Your AI illustration is ready. Switch between the views to compare. Your saved design remains the print reference.';pending=false;mode(true);
}catch(e){generatedFor=null;pending=false;mode(false);$('aiStatus').textContent=e.message==='design_changed'?'Your design changed while the preview was being made. Generate a new preview when you are ready.':e.message==='rate_limit'?'Preview requests are busy. Please wait a few minutes and try again. Your design is safe.':e.name==='AbortError'?'The preview took too long. You can try again; your design is safe.':'AI preview is temporarily unavailable. You can keep designing and saving your shirt, then try again later.';}
finally{clearTimeout(timeout);pending=false;$('aiProgress').hidden=true;$('aiView').disabled=generatedFor!==signature();$('aiPreviewBtn').disabled=false;$('aiPreviewBtn').textContent=generatedFor?'View my AI preview ↗':'See a realistic AI preview ↗';}};
counts();mode(false);
