import {client,login,fail,notify,requireWrites} from './member.js';import {money} from './design-model.js';
const $=id=>document.getElementById(id),detail=location.pathname.endsWith('finance-entry.html'),orderId=new URLSearchParams(location.search).get('order');let orderOffset=0,entryOffset=0,busy=false,requestSignature=null,requestKey=null,loadVersion=0;
const labels={cogs_product:'Printful / garment and printing',cogs_shipping:'Supplier shipping',cogs_supplier_tax:'Supplier tax',cogs_packaging:'Packaging',cogs_other:'Other fulfillment cost',payment_fee:'Payment processor fee',opex_software:'Software and hosting',opex_marketing:'Marketing',opex_other:'Other operating expense'};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let from='2000-01-01',to=today();if(!detail){const d=new Date(to+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-29);from=d.toISOString().slice(0,10);$('from').value=from;$('to').value=to;}
function el(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
const cash=v=>v===null||v===undefined?'Not reviewed':money(Number(v),'USD');
async function call(offset=0,body){const {data}=await client.auth.getSession();if(!data.session){login(detail?'/finance-entry.html'+(orderId?'?order='+encodeURIComponent(orderId):''):'/finances.html');throw new Error('Sign in with your owner account.');}const q=new URLSearchParams({from,to,offset:String(offset)});if(orderId)q.set('order',orderId);const r=await fetch('/api/finance'+(body?'':'?'+q),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const out=await r.json();if(!r.ok)throw new Error(out.error);return out;}
function metrics(root,pairs){root.replaceChildren();for(const [label,value] of pairs){const c=el('article','','card');c.append(el('p',label),el('strong',value));root.append(c);}}
function entries(data){const root=$('finance-entries');root.replaceChildren();if(!data.entries.length)root.append(el('p','No entries on this page. Record costs and expenses to begin.'));for(const e of data.entries){const c=el('article','','card');c.append(el('h3',labels[e.category]),el('p',cash(e.amount_minor)+' · '+e.basis+' · '+e.occurred_on),el('p',e.note),el('p',[e.provider,e.reference].filter(Boolean).join(' · ')));if(e.order_id){const a=el('a','Open order finances','secondary');a.href='/finance-entry.html?order='+e.order_id;c.append(a);}if(!e.reversed&&!e.reverses_id){const b=el('button','Reverse mistaken entry','secondary');b.onclick=async()=>{const reason=prompt('Reason for correcting this entry (the original will be preserved):');if(!reason?.trim())return;await mutation(b,{action:'entry',request_key:crypto.randomUUID(),reverses_id:e.id,note:reason.trim()});};c.append(b);}else c.append(el('p',e.reverses_id?'Correction reversal':'Reversed — original kept for history'));root.append(c);}$('entries-prev').hidden=entryOffset===0;$('entries-next').hidden=entryOffset+20>=data.entry_count;}
async function load(){const version=++loadVersion;const data=await call(orderOffset);const entryData=entryOffset===orderOffset?data:await call(entryOffset);if(version!==loadVersion)return;$('finance-content').hidden=false;entries(entryData);if(detail){if(orderId){const o=data.orders[0];if(!o)throw new Error('Paid USD order not found.');$('finance-title').textContent='Costs for order #'+o.order_number;$('order-financials').hidden=false;metrics($('order-summary'),[['Net revenue',cash(o.net_revenue)],['Actual fulfillment costs',cash(o.cogs_actual)],['Estimated fulfillment costs',cash(o.cogs_estimate)],['Actual payment fees',cash(o.fees_actual)],['Estimated payment fees',cash(o.fees_estimate)],['Gross profit'+(o.refund_estimated?' (provisional)':''),cash(o.gross_profit)],['Gross margin',o.gross_margin_percent===null?'Not available':o.gross_margin_percent+'%'],['Contribution after fees',cash(o.contribution)]]);$('cogs-complete').checked=o.cogs_complete;$('fees-complete').checked=o.fees_complete;$('refund-tax').value=o.recorded_refund_total_minor===o.refunded_minor&&o.recorded_refund_tax_minor!==null?(o.recorded_refund_tax_minor/100).toFixed(2):'';$('review-history').replaceChildren(...data.reviews.map(r=>el('p','Review '+new Date(r.created_at).toLocaleString()+': fulfillment '+(r.details.cogs_complete?'complete':'incomplete')+', fees '+(r.details.fees_complete?'complete':'incomplete'))));}return;}
 const s=data.summary;metrics($('finance-summary'),[['Net sales excluding tax',cash(s.net_revenue)],['Revenue refunded',cash(s.refunds_excluding_tax)],['Recorded fulfillment costs',cash(s.recorded_cogs)],['Gross profit'+(s.estimated_refunds?' (provisional)':''),cash(s.gross_profit)],['Gross margin',s.gross_margin_percent===null?'Not available':s.gross_margin_percent+'%'],['Payment fees recorded',cash(s.recorded_fees)],['Contribution after fees',cash(s.contribution)],['Operating expenses',cash(s.operating_expenses)],['After operating expenses',cash(s.after_expenses)],['Outstanding store credit (all time)',cash(data.credit_liability)],['Customer tax, net of refunds',cash(s.net_customer_tax)]]);$('coverage').textContent=s.order_count+' paid orders. '+s.missing_cogs+' with fulfillment costs not reviewed; '+s.missing_fees+' with fees not reviewed; '+s.estimated_refunds+' with provisional refund allocation. Profit totals require complete cost coverage.';
 const root=$('financial-orders');root.replaceChildren();if(!data.orders.length)root.append(el('p','No paid orders on this page.'));for(const o of data.orders){const c=el('article','','card');c.append(el('h3','Order #'+o.order_number),el('p','Net revenue '+cash(o.net_revenue)+' · gross profit '+cash(o.gross_profit)),el('p','Gross margin '+(o.gross_margin_percent===null?'not available':o.gross_margin_percent+'%')+' · '+o.payment_status.replaceAll('_',' ')),el('p',(o.cogs_complete?'Fulfillment reviewed':'Fulfillment costs incomplete')+' · '+(o.fees_complete?'Fees reviewed':'Fees incomplete')+(o.refund_estimated?' · provisional refund split':'')));const a=el('a','Review order costs','secondary');a.href='/finance-entry.html?order='+o.id;c.append(a);root.append(c);}$('orders-prev').hidden=orderOffset===0;$('orders-next').hidden=orderOffset+20>=s.order_count;}
async function mutation(button,body){if(busy)return;busy=true;button.disabled=true;try{requireWrites();await call(0,body);notify('Financial record saved.');requestSignature=null;requestKey=null;await load();return true;}catch(e){fail(e);return false;}finally{busy=false;button.disabled=false;}}
if(detail){for(const [value,label] of Object.entries(labels).filter(([k])=>orderId?!k.startsWith('opex_'):k.startsWith('opex_'))){const o=el('option',label);o.value=value;$('category').append(o);}$('occurred').value=today();$('entry-form').onsubmit=async e=>{e.preventDefault();const amount=Math.round(Number($('amount').value)*100)*($('cost-credit').checked?-1:1);const body={action:'entry',order_id:orderId||null,category:$('category').value,basis:$('basis').value,amount_minor:amount,occurred_on:$('occurred').value,provider:$('provider').value,reference:$('reference').value,note:$('note').value};const signature=JSON.stringify(body);if(requestSignature!==signature){requestSignature=signature;requestKey=crypto.randomUUID();}if(await mutation(e.submitter,{...body,request_key:requestKey})){$('amount').value='';$('note').value='';$('reference').value='';$('cost-credit').checked=false;}};$('review-form').onsubmit=e=>{e.preventDefault();mutation(e.submitter,{action:'review',order_id:orderId,cogs_complete:$('cogs-complete').checked,fees_complete:$('fees-complete').checked,refund_tax_minor:$('refund-tax').value===''?null:Math.round(Number($('refund-tax').value)*100)});};}
else{$('period-form').onsubmit=e=>{e.preventDefault();from=$('from').value;to=$('to').value;orderOffset=entryOffset=0;load().catch(fail);};$('orders-prev').onclick=()=>{orderOffset=Math.max(0,orderOffset-20);load().catch(fail);};$('orders-next').onclick=()=>{orderOffset+=20;load().catch(fail);};}
$('entries-prev').onclick=()=>{entryOffset=Math.max(0,entryOffset-20);load().catch(fail);};$('entries-next').onclick=()=>{entryOffset+=20;load().catch(fail);};
load().catch(fail);
