const path=location.pathname;
const demoPage=path==='/try.html';
let demo=false;try{demo=sessionStorage.getItem('notai-demo')==='true';}catch{}
const tab=new URLSearchParams(location.search).get('tab')||'account';
const pageKey=demoPage?tab:document.body.dataset.page||'designer';
const href=(key,url)=>demo&&key!=='sizes'?'/try.html?tab='+key:url;
function link(label,url,key){const a=document.createElement('a');a.textContent=label;a.href=url;a.className='nav-button';if(key===pageKey){a.setAttribute('aria-current','page');}return a;}
const old=document.querySelector('header')||document.querySelector('.top');
if(old){const header=document.createElement('header');header.className='site-header';const brand=link('Not AI, Just I.','/','brand');brand.className='site-brand';brand.replaceChildren(document.createTextNode('Not AI, Just '));const human=document.createElement('span');human.className='human-i';human.textContent='I.';brand.append(human);const nav=document.createElement('nav');nav.className='site-nav';nav.setAttribute('aria-label','Main navigation');const primary=document.createElement('div');primary.className='nav-primary';primary.append(link('Create a shirt','/','designer'),link(demo?'Browser designs':'My designs',href('designs','/designs.html'),'designs'),link(demo?'Demo profile':'My account',href('account','/account.html'),'account'),link(demo?'Save to account':'Try without sign-in',demo?'/signup.html':'/try.html',demo?'signup':'demo'));
const more=document.createElement('details');more.className='nav-more';const summary=document.createElement('summary');summary.textContent='Orders, credits & more';more.append(summary);const group=document.createElement('div');group.className='nav-secondary';for(const [key,label,url] of [['orders','Orders','/orders.html'],['credits','Referral credits','/credits.html'],['network','Human Network','/network.html'],['shares','Shared designs','/shares.html'],['gifts','Gifts','/gifts.html'],['sizes','Size guide','/sizes.html']])group.append(link(label,href(key,url),key));more.append(group);if(['orders','order','credits','network','shares','gifts','sizes'].includes(pageKey))more.open=true;nav.append(primary,more);header.append(brand,nav);old.replaceWith(header);}
const guides={designer:['Create your shirt','1. Choose your words and style. 2. Save your design. 3. Review the proof before ordering.'],account:['Your account','Manage your profile here. Use My designs to find saved ideas, or Create a shirt to start a new one.'],designs:['Your saved ideas','Edit a design, make a copy, or restore an earlier version. Review and order when you are ready.'],orders:['Purchases & delivery','Find your orders here. Open an order to see its payment, shipment and tracking details.'],credits:['Referral rewards','Your earned credits and referral history appear here. Sample credits in the demo cannot be spent.'],network:['Your Human Network','Explore the connections inspired by your shirts. Manage your shirt stories and QR privacy here.'],shares:['Links you control','Find your shared designs here and revoke links you no longer want to share.'],gifts:['Give someone a shirt','Create an invitation, let the recipient choose a design, then review their choice before purchasing.'],signup:['Save your ideas to an account','Create an account, confirm your email, then import your browser drafts from My account.'],signin:['Welcome back','Sign in to open your account and saved designs. You can also explore using Try without sign-in.'],proof:['Review before ordering','Check the words, icon and layout carefully, then continue to choose an available size.'],checkout:['Choose size & checkout','Review the design, select a size and quantity, then continue to secure payment when ordering is open.']};
const host=document.querySelector('main')||document.querySelector('.wrap');
if(host&&guides[pageKey]&&!demoPage){const section=document.createElement('section');section.className='page-guide';const strong=document.createElement('strong');strong.textContent=guides[pageKey][0];const p=document.createElement('p');p.textContent=guides[pageKey][1];section.append(strong,p);host.prepend(section);}
// Links keep their native link semantics while receiving a consistent touch target.
for(const a of document.querySelectorAll('main a,.wrap a')){if(a.id==='proof-link'||a.querySelector('img'))continue;a.classList.add('page-link');}

const actions=document.querySelector('.demo-actions');const demoContent=document.getElementById('demo-content');if(actions&&demoContent)demoContent.after(actions);

// Discover owner controls from protected membership, never from editable profile metadata.
if(!demo)import('./member.js').then(async({client})=>{const {data}=await client.auth.getSession();if(!data.session||data.session.user.is_anonymous)return;const r=await client.from('shop_owners').select('auth_user_id').eq('auth_user_id',data.session.user.id).maybeSingle();if(!r.error&&r.data){const group=document.querySelector('.nav-secondary');if(group)group.append(link('Owner dashboard','/owner.html','owner'));}}).catch(()=>{});
