import {client,login,notify,fail,requireWrites} from './member.js';import {money} from './design-model.js';
const $=id=>document.getElementById(id);let data;
async function call(body){const {data:s}=await client.auth.getSession();if(!s.session){login('/owner.html');throw new Error('Sign in with your owner account.');}const r=await fetch('/api/owner',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+s.session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;}
function el(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
function clear(){ $('variant-form').reset();$('variant-id').value='';$('product-name').value='Not AI, Just I — personalized shirt';$('price').value='27.99';$('supplier').value='Manual';}
function edit(v){for(const [id,k] of [['variant-id','id'],['sku','sku'],['product-name','product_name'],['color','color_key'],['size','size_key'],['supplier','fulfillment_provider'],['supplier-id','provider_variant_id']])$(id).value=v[k]||'';$('price').value=(v.price_minor/100).toFixed(2);$('active').checked=v.active;$('variant-form').scrollIntoView({behavior:'smooth'});}
async function load(){data=await call();$('owner-content').hidden=false;const r=data.readiness;$('payment-state').textContent='Payment mode: '+r.mode+'. '+(data.settings?.ordering_open&&r.database&&r.stripe&&r.webhook&&r.enabled&&r.mode==='live'?'Ordering is open.':'Ordering is closed until setup is complete.');$('readiness').replaceChildren(...[['database','Server database key'],['stripe','Stripe API key'],['webhook','Webhook signing secret'],['enabled','Server ordering switch']].map(([k,label])=>el('li',label+': '+(r[k]?'Present':'Missing'))));for(const id of ['settings-form','variant-form'])for(const control of $(id).elements)control.disabled=!r.database;if(data.settings){$('shipping').value=(data.settings.shipping_minor/100).toFixed(2);$('fulfillment-note').value=data.settings.fulfillment_note;$('ordering-open').checked=data.settings.ordering_open;}
 $('products').replaceChildren();for(const v of data.variants){const card=el('article','');card.className='card';card.append(el('h3',v.product_name+' · '+v.color_key+' · '+v.size_key),el('p',v.sku+' · '+money(v.price_minor,v.currency)+' · '+(v.active?'Available':'Inactive')));const b=el('button','Edit product');b.className='secondary';b.onclick=()=>edit(v);card.append(b);$('products').append(card);}
 $('owner-orders').replaceChildren();if(!data.orders.length)$('owner-orders').append(el('p','No orders yet. Finish setup, then test a full checkout before opening real sales.'));for(const o of data.orders){const c=el('article','');c.className='card';c.append(el('h3','Order #'+o.order_number),el('p',money(o.total_minor,o.currency)+' · '+o.payment_status.replaceAll('_',' ')+' · '+o.fulfillment_status.replaceAll('_',' ')));if(o.payment_status==='paid'&&o.fulfillment_status==='unfulfilled'){const b=el('button','Start production');b.className='secondary';b.onclick=()=>action(b,{action:'production',order_id:o.id});c.append(b);}$('owner-orders').append(c);}}
async function action(button,body){button.disabled=true;try{requireWrites();await call(body);notify('Saved.');await load();}catch(e){fail(e);}finally{button.disabled=false;}}
$('settings-form').onsubmit=e=>{e.preventDefault();action(e.submitter,{action:'settings',shipping_minor:Math.round(Number($('shipping').value)*100),fulfillment_note:$('fulfillment-note').value,ordering_open:$('ordering-open').checked});};
$('variant-form').onsubmit=e=>{e.preventDefault();action(e.submitter,{action:'variant',id:$('variant-id').value||null,sku:$('sku').value,product_name:$('product-name').value,color_key:$('color').value,size_key:$('size').value,price_minor:Math.round(Number($('price').value)*100),active:$('active').checked,fulfillment_provider:$('supplier').value,provider_variant_id:$('supplier-id').value});};
$('new-product').onclick=clear;$('refresh').onclick=()=>load().catch(fail);clear();load().catch(fail);
