import {client,login,fail,notify,requireWrites} from './member.js';
const $=id=>document.getElementById(id);let mode='owners',search='',cursor=null,pages=[],nextCursor=null,busy=false,chosen=null,selfId;
function el(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
async function call(body){const {data}=await client.auth.getSession();if(!data.session){login('/owner-access.html');throw new Error('Sign in with your owner account.');}const query=new URLSearchParams({mode,search});if(cursor)query.set('cursor',cursor);const r=await fetch('/api/owner-access'+(body?'':'?'+query),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;}
function controls(disabled){for(const id of ['show-owners','previous','next'])$(id).disabled=disabled;$('search-form').querySelector('button').disabled=disabled;}
async function load(){if(busy)return;busy=true;controls(true);try{const data=await call();selfId=data.self_id;nextCursor=data.next_cursor;$('access-content').hidden=false;$('owner-count').textContent=data.owner_count+' owner'+(data.owner_count===1?'':'s')+'. At least one must remain.';$('results-title').textContent=mode==='owners'?'Current owners':'User search results';$('previous').hidden=!pages.length;$('next').hidden=!nextCursor;$('access-results').replaceChildren();if(!data.users.length)$('access-results').append(el('p','No matching users. Try the beginning of their email address.'));for(const u of data.users){const card=el('article','');card.className='card';card.append(el('h3',u.full_name||u.email||'User'),el('p',u.email||'No email address'),el('p',(u.handle?'@'+u.handle+' · ':'')+(u.is_owner?'Owner':'Customer')+(u.id===selfId?' · You':'')));const b=el('button',u.is_owner?'Remove owner access':'Grant owner access');b.className='secondary';b.disabled=u.is_owner?data.owner_count<=1:!u.eligible;if(b.disabled)card.append(el('p',u.is_owner?'This is the last owner. Add another owner before removing access.':'This user must confirm their email and have an active account first.'));b.onclick=()=>{chosen={id:u.id,grant:!u.is_owner};$('confirm-title').textContent=chosen.grant?'Grant owner access?':'Remove owner access?';$('confirm-user').textContent=u.email||u.full_name;$('confirm-warning').textContent=chosen.grant?'This person will have full control of shop settings, orders, fulfillment and owner access.':u.id===selfId?'This removes your own owner access. You will lose access to the dashboard immediately.':'This person will lose owner access on subsequent requests. Their customer account and orders remain.';$('confirm-access').showModal();};card.append(b);$('access-results').append(card);}$('access-events').replaceChildren();if(!data.events.length)$('access-events').append(el('p','No access changes recorded yet.'));for(const e of data.events)$('access-events').append(el('p',e.actor+' '+e.action+' access for '+e.target+' · '+new Date(e.created_at).toLocaleString()));}catch(e){fail(e);}finally{busy=false;controls(false);}}
$('search-form').onsubmit=e=>{e.preventDefault();mode='users';search=$('user-search').value.trim();cursor=null;pages=[];load();};$('show-owners').onclick=()=>{mode='owners';search='';cursor=null;pages=[];load();};$('next').onclick=()=>{pages.push(cursor);cursor=nextCursor;load();};$('previous').onclick=()=>{cursor=pages.pop();load();};
$('confirm-access').addEventListener('close',async()=>{if($('confirm-access').returnValue!=='confirm'||!chosen||busy)return;busy=true;controls(true);try{requireWrites();const selected=chosen;await call({user_id:selected.id,grant:selected.grant,confirmed:true});notify(selected.grant?'Owner access granted.':'Owner access removed.');if(!selected.grant&&selected.id===selfId){$('access-content').hidden=true;location.assign('/account.html');return;}}catch(e){fail(e);}finally{chosen=null;busy=false;controls(false);}await load();});
load();
