import {readDrafts,storeDrafts,saveGuestProfile,stopDemo} from './guest.js';
import {artwork} from './proof.js';
sessionStorage.setItem('notai-demo','true');
const root=document.getElementById('demo-content'),status=document.getElementById('status');
const tab=new URLSearchParams(location.search).get('tab')||'account';
document.getElementById('demo-title').textContent=({account:'My demo profile.',designs:'My browser designs.',orders:'Sample orders.',credits:'Sample referral credits.',network:'Sample Human Network.',shares:'Sample sharing.',gifts:'Sample gifts.'}[tab]||'Explore the demo.');
const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
function button(text,fn){const b=el('button',text);b.onclick=()=>{try{fn();}catch(e){status.textContent=e.message;}};return b;}
function render(){root.replaceChildren();const data=readDrafts();if(tab==='account'){const form=el('form');form.innerHTML='<h2>My demo profile</h2><label for="demo-name">Your name</label><input id="demo-name" required maxlength="200"><label for="demo-handle">Public handle (optional)</label><input id="demo-handle" maxlength="30"><label class="check"><input id="demo-public" type="checkbox">Let my handle appear in the Human Network after I save to an account</label><p>Nothing entered here is published. Handle availability is checked when saved to your account.</p><button type="submit">Save demo profile</button>';form.querySelector('#demo-name').value=data.profile.full_name;form.querySelector('#demo-handle').value=data.profile.handle||'';form.querySelector('#demo-public').checked=data.profile.network_visibility==='public';form.onsubmit=e=>{e.preventDefault();try{saveGuestProfile({full_name:form.querySelector('#demo-name').value,handle:form.querySelector('#demo-handle').value,network_visibility:form.querySelector('#demo-public').checked?'public':'private'});status.textContent='Profile saved in this browser.';}catch(e){status.textContent=e.message;}};root.append(form);}
else if(tab==='designs'){root.append(el('h2','My browser drafts'));if(!data.designs.length)root.append(el('p','No drafts yet. Create a shirt design above, then save it in this browser.'));for(const d of data.designs){const card=el('article');card.className='card';card.append(el('h3',d.name+(d.archived?' (archived)':'')),el('p',d.versions.length+' saved versions'));const img=el('img');img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(artwork(d.versions.at(-1)));img.alt='Artwork for '+d.name;img.style.cssText='max-width:200px;background:#333';card.append(img);const edit=el('a','Edit design');edit.href='/index.html?draft='+d.id;card.append(edit,button(d.archived?'Restore':'Archive',()=>{d.archived=!d.archived;storeDrafts(data);render();}),button('Delete draft',()=>{data.designs=data.designs.filter(x=>x.id!==d.id);storeDrafts(data);render();}));root.append(card);}}
else{root.append(el('h2','Sample '+({orders:'orders',credits:'credits',network:'Human Network',shares:'sharing',gifts:'gifts'}[tab]||'account page')),el('p','Illustration only. These are sample records, not real purchases, credits, connections or links.'));const examples={orders:['Sample order #DEMO-001','Payment: paid (sample) · Shipped (sample)','One personalized shirt · Tracking shown here after a real shipment.'],credits:['Sample balance: $6.00','Two qualifying referrals at $3 each (sample). No spendable credit exists.'],network:['You → @sample_soccer → Private human','Real connections appear only after qualifying paid referrals.'],shares:['Share a saved version and revoke its link later.','Browser drafts remain private; create an account to generate a real sharing link.'],gifts:['Invite someone to choose a design and size.','Review their choice before paying. A sample invitation charges nothing.']};for(const text of examples[tab]||[]){const p=el('p',text);p.className='sample-notice';root.append(p);}}}
for(const id of ['register','sign-in'])document.getElementById(id).onclick=stopDemo;
document.getElementById('exit').onclick=()=>{stopDemo();location.assign('/');};
document.getElementById('clear').onclick=()=>document.getElementById('clear-confirm').hidden=false;
document.getElementById('cancel-clear').onclick=()=>document.getElementById('clear-confirm').hidden=true;
document.getElementById('confirm-clear').onclick=()=>{localStorage.removeItem('notai-browser-drafts-v1');document.getElementById('clear-confirm').hidden=true;status.textContent='Browser drafts and preferences cleared.';render();};render();
