begin;
create index on public.design_assets (revision_id,user_id);
create index on public.design_revisions (design_id,user_id);
create index on public.order_items (order_id,user_id);
create index on public.order_items (revision_id,user_id);
create index on public.referral_attributions (order_id,buyer_id);
create index on public.referral_attributions (source_shirt_id,referrer_id);
create index on public.shipment_shirts (shipment_id,user_id);
create index on public.shipment_shirts (shirt_id,user_id);
create index on public.shipments (order_id,user_id);
create index on public.shirts (order_item_id,user_id);
alter policy own_profile on public.profiles using (auth_user_id=(select auth.uid()) and ((select auth.jwt())->>'is_anonymous')::boolean is false);
commit;
