create or replace function notai_private.finance_report(p_from date,p_to date,p_offset integer default 0,p_order uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid:=auth.uid();result jsonb;begin
 if actor is null or not exists(select 1 from public.shop_owners where auth_user_id=actor) then raise exception 'Owner access required.' using errcode='42501';end if;
 if p_from is null or p_to is null or p_to<p_from or p_offset is null or p_offset<0 or p_offset>100000 then raise exception 'Check dates and page.';end if;
 if p_order is not null and not exists(select 1 from public.orders where id=p_order and currency='USD' and payment_status in('paid','partially_refunded','refunded')) then raise exception 'Paid USD order not found.';end if;
 with selected as(select * from notai_private.finance_order_metrics where (p_order is not null and id=p_order) or (p_order is null and created_at >= (p_from::timestamp at time zone 'America/Chicago') and created_at < ((p_to+1)::timestamp at time zone 'America/Chicago'))),summary as(
 select count(*) as order_count,coalesce(sum(original_revenue),0) as sales_before_refunds,coalesce(sum(revenue_refunded),0) as refunds_excluding_tax,coalesce(sum(net_revenue),0) as net_revenue,coalesce(sum(tax_minor-tax_refunded),0) as net_customer_tax,
 coalesce(sum(cogs_actual),0) as recorded_cogs,coalesce(sum(fees_actual),0) as recorded_fees,count(*) filter(where not cogs_complete) as missing_cogs,count(*) filter(where not fees_complete) as missing_fees,count(*) filter(where refund_estimated) as estimated_refunds,
 case when bool_and(cogs_complete) or count(*)=0 then coalesce(sum(gross_profit),0) else null end as gross_profit,
 case when bool_and(cogs_complete and fees_complete) or count(*)=0 then coalesce(sum(contribution),0) else null end as contribution,
 coalesce(sum(gross_profit) filter(where cogs_complete),0) as reviewed_gross_profit,count(*) filter(where cogs_complete) as reviewed_orders from selected),
 page as(select * from selected order by created_at desc,id desc limit 20 offset p_offset),
 expenses as(select coalesce(sum(amount_minor),0) as operating_expenses from notai_private.finance_entries where category like 'opex_%' and basis='actual' and occurred_on between p_from and p_to)
 select jsonb_build_object('currency','USD','summary',(select to_jsonb(s)||jsonb_build_object('gross_margin_percent',case when s.gross_profit is not null and s.net_revenue>0 then round(100.0*s.gross_profit/s.net_revenue,2) else null end,'operating_expenses',e.operating_expenses,'after_expenses',case when s.contribution is not null then s.contribution-e.operating_expenses else null end) from summary s cross join expenses e),'orders',coalesce((select jsonb_agg(to_jsonb(page) order by created_at desc,id desc) from page),'[]'::jsonb),
 'entries',coalesce((select jsonb_agg(to_jsonb(e) order by e.occurred_on desc,e.created_at desc,e.id desc) from(select f.*,exists(select 1 from notai_private.finance_entries r where r.reverses_id=f.id) as reversed from notai_private.finance_entries f where (p_order is not null and f.order_id=p_order) or (p_order is null and f.occurred_on between p_from and p_to) order by f.occurred_on desc,f.created_at desc,f.id desc limit 20 offset p_offset)e),'[]'::jsonb),
 'entry_count',(select count(*) from notai_private.finance_entries f where (p_order is not null and f.order_id=p_order) or (p_order is null and f.occurred_on between p_from and p_to)),
 'credit_liability',(select coalesce(sum(greatest(balance,0)),0) from(select sum(amount_minor) as balance from public.credit_ledger where currency='USD' group by user_id)b),
 'reviews',case when p_order is not null then coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from(select actor_id,details,created_at from notai_private.finance_review_events where order_id=p_order order by created_at desc limit 10)r),'[]'::jsonb) else '[]'::jsonb end) into result;
 return result;
end $$;
