import {db,gate,stripe,authenticated,respondError,noStore,validUuid,checkoutOrigin} from '../lib/server.js';
export default async function handler(req,res){noStore(res);if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).end();}try{
 gate();const returnOrigin=checkoutOrigin();const user=await authenticated(req);const b=typeof req.body==='string'?JSON.parse(req.body):req.body;
 if(!b||!validUuid(b.revision_id)||!validUuid(b.variant_id)||!validUuid(b.request_key)||!Number.isInteger(b.quantity)||b.quantity<1||b.quantity>10||b.proof_confirmed!==true)throw Object.assign(new Error('Review your design, size, and quantity first.'),{status:400});
 const shipping=Number(process.env.NOTAI_SHIPPING_MINOR);if(!Number.isSafeInteger(shipping)||shipping<0||shipping>100000)throw Object.assign(new Error('Shipping setup is not complete.'),{status:503});
 const store=db();const order=await store.rpc('prepare_order',{p_auth_user:user.id,p_revision:b.revision_id,p_variant:b.variant_id,p_quantity:b.quantity,p_shipping_minor:shipping,p_referral:typeof b.referral==='string'&&/^[a-f0-9]{32}$/.test(b.referral)?b.referral:null,p_key:b.request_key,p_gift:typeof b.gift==='string'&&/^[a-f0-9]{32}$/.test(b.gift)?b.gift:null,p_use_credit:b.use_credit===true});if(order.error)throw Object.assign(new Error('That design or product is unavailable. Please review your selection.'),{status:400});
 const o=order.data;if(o.payment_status!=='pending')throw Object.assign(new Error('This checkout has already finished. Check your orders.'),{status:409});
 const cancel=new URLSearchParams({revision:b.revision_id,variant:b.variant_id,quantity:String(b.quantity),credit:b.use_credit===true?'true':'false'});if(b.gift)cancel.set('gift',b.gift);
 const payments=stripe();let session;
 if(o.stripe_session_id)session=await payments.checkout.sessions.retrieve(o.stripe_session_id);else{
 let discounts=[];if(o.credit_minor>0){const coupon=await payments.coupons.create({amount_off:o.credit_minor,currency:o.currency.toLowerCase(),duration:'once',name:'NotAI store credit'},{idempotencyKey:'notai-credit-'+o.id});discounts=[{coupon:coupon.id}];}
 session=await payments.checkout.sessions.create({mode:'payment',discounts,customer_email:user.email,client_reference_id:o.id,metadata:{order_id:o.id},payment_intent_data:{metadata:{order_id:o.id},receipt_email:user.email},line_items:[{price_data:{currency:o.currency.toLowerCase(),unit_amount:o.subtotal_minor/b.quantity,tax_behavior:'exclusive',product_data:{name:'Not AI, Just I — personalized shirt',tax_code:'txcd_30011000'}},quantity:b.quantity}],shipping_address_collection:{allowed_countries:['US']},shipping_options:[{shipping_rate_data:{type:'fixed_amount',fixed_amount:{amount:o.shipping_minor,currency:o.currency.toLowerCase()},display_name:'Shipping',tax_behavior:'exclusive',tax_code:'txcd_92010001'}}],automatic_tax:{enabled:true},success_url:returnOrigin+'/order.html?id='+o.id,cancel_url:returnOrigin+'/checkout.html?'+cancel.toString()},{idempotencyKey:'notai-order-'+o.id});
 const update=await store.from('orders').update({stripe_session_id:session.id}).eq('id',o.id).eq('payment_status','pending');if(update.error)throw update.error;
 }
 if(!session.url||session.status!=='open')throw Object.assign(new Error('This checkout is closed. Start a new checkout.'),{status:409});res.status(200).json({url:session.url,order_id:o.id});
 }catch(e){respondError(res,e);}}
